# services:
#   backend:
#     env_file:
#         ".env"
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     image: "akkarachajaitrong/pre_edoc-backend"
#     ports:
#       - "3000:3000"
#   frontend:
#     build:
#       context: ./hello-app
#       dockerfile: Dockerfile
#     image: "akkarachajaitrong/pre_edoc-frontend"
#     ports:
#       - "3001:3001"
#     links:
#       - "backend:be"
#     networks:
#       - external_network # ใช้ external network

# networks:
#   external_network:
#     external: true

# services:
#   backend:
#     env_file:
#       - ".env"
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     image: "akkarachajaitrong/pre_edoc-backend"
#     ports:
#       - "3000:3000"

#   frontend:
#     build:
#       context: ./hello-app
#       dockerfile: Dockerfile
#     image: "akkarachajaitrong/pre_edoc-frontend"
#     ports:
#       - "3001:3001"  # ตรวจสอบให้แน่ใจว่า frontend รันที่พอร์ต 3001
#     depends_on:
#       - backend  # ตรวจสอบว่า backend รันก่อน
#     networks:
#       - external_network  # ใช้ external network

# networks:
#   external_network:
#     external: true  # ใช้ external network ที่คุณสร้างไว้
# version: '3.8'

version: '3.8'

services:
  backend:
    env_file:
      - ".env" # โหลดตัวแปรจากไฟล์ .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "akkarachajaitrong/pre_edoc-backend"
    ports:
      - "3000:3000" # Backend ใช้พอร์ต 3000
    environment:
      # กำหนดค่าตัวแปรสภาพแวดล้อมสำหรับเชื่อมต่อ MySQL
      DB_HOST: mysql # ใช้ mysql แทน localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 80945 # ปรับให้ตรงกับค่าที่ใช้ใน .env
      DB_NAME: register
    networks:
      - external_network
    depends_on:
      - mysql
    entrypoint: [ "sh", "/app/entrypoint.sh" ] # ใช้ entrypoint.sh เพื่อรอให้ MySQL พร้อมใช้งาน

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 80945 # ต้องตรงกับค่าที่ใช้ใน backend
      MYSQL_DATABASE: register
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 080945

    ports:
      - "3306:3306"
    networks:
      - external_network

  frontend:
    build:
      context: ./hello-app
      dockerfile: Dockerfile
    image: "akkarachajaitrong/pre_edoc-frontend"
    ports:
      - "3001:3001" # Frontend ใช้พอร์ต 3001
    depends_on:
      - backend
    networks:
      - external_network

networks:
  external_network:
    external: true # ใช้ external network ที่คุณสร้างไว้
